пробный набросок лесса
htmlacademy-adaptive/1981775-sedona-25 pull request #5
Opened 2022-04-12 16:53 UTC by Alexanderrrrrrrrrrr

2022-04-12 17:32 UTC, baronin requested changes
Пол пути сделали, еще осталось немного :) 

Нужно поправить lint ошибки с stylelint

<img width="617" alt="image" src="https://user-images.githubusercontent.com/20131942/163020478-0b089f5b-2a68-4b3f-b441-d21e2f837bee.png">

2022-04-12 17:32 UTC, baronin commented on source/sass/style.scss
> +@import "./blocks/secondary-text.scss";
Когда запускаем проект, показывает ошибку
<img width="385" alt="image" src="https://user-images.githubusercontent.com/20131942/163016579-28914841-a9e2-47f0-bbb6-886ed2697622.png">

Я зашел что бы проверить, есть ли этот файл в папке blocks - но его там действительно нет

2022-04-12 17:32 UTC, baronin commented on source/sass/style.scss
> +@import "./blocks/page__body.scss";
в файловой структуре scss не нужно разбивать как по БЭМу, по БЭМу мы разбиваем только разметку

просто называй файлы через тире, page-body

2022-04-12 17:32 UTC, baronin commented on source/sass/style.scss
> +@import "./blocks/fonts.scss";
Мы должны соблюдать иерархию загрузки стилей

В первую очередь мы должны сделать импорт всех основных стилей как fonts, visually-hidden и то что с текстом связано

А потом уже остальные основные блоки

2022-04-12 17:32 UTC, baronin commented on source/catalog 2.html
> +<!DOCTYPE html>
Подскажи, что это за файлы catalog2 и form 2 ? Это наверное из другого проекта, давай их удалим

2022-04-12 17:32 UTC, baronin commented on source/sass/blocks/benefits__item.scss
> +  background-color: hsl(0, 0%, 93%);
Мы не используем hsl в проекте, только hex цвета, замени везде hsl на hex(hex - выглядит так #81B3D2)

2022-04-12 17:32 UTC, baronin commented on source/sass/blocks/main-header.scss
> +  weight: 768px;
weight - в переводе как жирность, мы не можем в пикселях жирность задать

2022-04-12 17:32 UTC, baronin commented on source/sass/blocks/main-nav__list.scss
> +.main-nav__list {
У нас есть критерий Б28, не проходим по нему 
![image](https://user-images.githubusercontent.com/20131942/163018583-9053c510-c17e-47ce-88f8-b11ebefd47c8.png)

2022-04-12 17:32 UTC, baronin commented on source/sass/blocks/fonts.scss
> +  src: url("../fonts/ptsans-400.woff2") format("woff2");
ptsans-400.woff2 - зашел к тебе в папку с fonts и не нашел там шрифта такого
И в консоле тоже ругается что нет этого шрифта ну и второго аналогично

<img width="548" alt="image" src="https://user-images.githubusercontent.com/20131942/163019462-d9e8b527-d9fc-4a44-bd2f-898f7997f44a.png">

2022-04-12 17:32 UTC, baronin commented on source/sass/blocks/body.scss
> +body {
![image](https://user-images.githubusercontent.com/20131942/163019726-d33b6e00-fc97-4874-be18-e5d6402ef36e.png)

2022-04-12 17:32 UTC, baronin commented on .stylelintrc
> +    "at-rule-no-unknown": null
Откуда это взялось ? мы не можем добавлять какие либо изменения в настройки проекта

2022-04-12 17:35 UTC, baronin commented on source/catalog 2.html
> +              Главная
Не хватает стиле для текста в навигации и отступов
<img width="253" alt="image" src="https://user-images.githubusercontent.com/20131942/163021024-a6510481-9d6e-4e60-a175-f5ae50064dfe.png">

2022-04-12 17:36 UTC, baronin commented on source/catalog 2.html
> +              <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
не хватает стилей для текста 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/20131942/163021118-4a96b38d-3e73-4e44-8001-72730ec5c218.png">

![image](https://user-images.githubusercontent.com/20131942/163021176-f34190fd-d59f-41ec-a61a-53b50c68fcf9.png)

2022-04-12 17:38 UTC, baronin commented on source/index.html
>            <li class="benefits__item">
У тебя есть бэкграунт на макете серый в этих блоках
<img width="397" alt="image" src="https://user-images.githubusercontent.com/20131942/163021553-9e099eb5-63ae-492b-bf52-26ab94c5df1e.png">

2022-04-13 13:45 UTC, Alexanderrrrrrrrrrr commented on source/sass/style.scss
> +@import "./blocks/secondary-text.scss";
вроде всё есть

2022-04-13 13:45 UTC, Alexanderrrrrrrrrrr commented on source/sass/style.scss
> +@import "./blocks/page__body.scss";
исправил

2022-04-13 13:46 UTC, Alexanderrrrrrrrrrr commented on source/sass/style.scss
> +@import "./blocks/fonts.scss";
тут нужно поподробнее

2022-04-13 13:46 UTC, Alexanderrrrrrrrrrr commented on source/catalog 2.html
> +<!DOCTYPE html>
не знаю я их не делал

2022-04-13 13:46 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/benefits__item.scss
> +  background-color: hsl(0, 0%, 93%);
поправил

2022-04-13 13:46 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/main-header.scss
> +  weight: 768px;
поправил

2022-04-13 13:46 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/main-nav__list.scss
> +.main-nav__list {
поправил

2022-04-13 13:47 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/fonts.scss
> +  src: url("../fonts/ptsans-400.woff2") format("woff2");
вроде подключил

2022-04-13 13:47 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/body.scss
> +body {
убрал

2022-04-13 13:47 UTC, Alexanderrrrrrrrrrr commented on .stylelintrc
> +    "at-rule-no-unknown": null
это я из видео взял они сказали если используешь ссас нужно добавить

2022-04-18 17:37 UTC, baronin requested changes
Работаем дальше :)

2022-04-18 17:37 UTC, baronin commented on source/sass/blocks/html.scss
> +html {
Уже писал за то что мы не стилим теги, у нас есть критейри по этому пункту

2022-04-18 17:37 UTC, baronin commented on source/sass/blocks/page-body.scss
> +.page__body {
А кто родитель у page__body ? Элемент есть, а где блок ?

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <a class="site-list__text">
Думаю эта ссылка должна вести на каталог

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <a class="site-list__text">
Думаю эта ссылка должна вести на форму

2022-04-18 17:37 UTC, baronin commented on source/sass/blocks/main-nav-list.scss
> +  width: 700;
width - принимает значения в px, %, rem, em
а тут какое ?)

2022-04-18 17:37 UTC, baronin commented on source/sass/blocks/preview-title.scss
> +.preview__title {
Не задан шрифт, в макете PT Sans, у тебя Times New Roman и так весь текст
![image](https://user-images.githubusercontent.com/20131942/163846247-7a175548-d60f-43ab-a32c-592f2dea3b29.png)

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy"><img class="vk" src="/source/img/vk.svg" width="48" height="48" alt="vk"></a>
Иконки добавь не через img , а инлайново svg
_Пример:_
![image](https://user-images.githubusercontent.com/20131942/163846651-de29a821-47bb-47ab-ac52-fdd7ff277217.png)

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <img class="city__foto" src="img/photo-city@1x 1.jpg" width="520" height="260"
тег article  должен содержать в себе заголовки
https://qna.habr.com/q/374950 - тут хорошо расписали )

Тут ты можешь проверить свой html  файл на валидность кода
https://validator.w3.org/#validate_by_upload

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <img class="devil-bridge__foto" src="img/photo-bridge@1x 1.jpg" width="520" height="260" alt="Мост дьявола">
за это я уже писал выше, артикл без заголовка не может быть
Да и на макете если мы посмотрим то devil -  devil-bridge это один не разделенный блок

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +            <h1 class="second-list__title secondary-text">Небольшая площадь</h1>
Мы уже проходили с тобой что тег h1 только один  может на странице

2022-04-18 17:37 UTC, baronin commented on source/index.html
> +        <div class="benefits__list">
Скорей всего это лишний div.benefits__list

2022-04-19 10:58 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/html.scss
> +html {
удалил

2022-04-19 10:58 UTC, Alexanderrrrrrrrrrr commented on source/sass/blocks/page-body.scss
> +.page__body {
сделал блоком

2022-04-19 15:04 UTC, Alexanderrrrrrrrrrr commented on source/index.html
> +            <img class="city__foto" src="img/photo-city@1x 1.jpg" width="520" height="260"
поправил

2022-04-19 15:04 UTC, Alexanderrrrrrrrrrr commented on source/index.html
> +            <img class="devil-bridge__foto" src="img/photo-bridge@1x 1.jpg" width="520" height="260" alt="Мост дьявола">
объединил в один блок

2022-05-10 21:14 UTC, baronin commented on source/sass/blocks/preview-text.scss
>  .preview__text {
где у текста родитель блока? 
Блок элемент модификатор 
block__element--modificator
в БЭМ без блока не может быть эелемента

2023-02-15 17:58 UTC, closed without merging